### PR TITLE
Execute tests for PRs

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Comment by atodorov** [comment]
@rvinzent can you please review ?

**Review by rvinzent — APPROVED** [review]

**Comment by rvinzent** [comment]
@atodorov thanks for the contribution!

**Comment by atodorov** [comment]
> @atodorov thanks for the contribution!

You're welcome. I need you to click the "Merge" button though. I can't do that on my own.

**Comment by rvinzent** [comment]
> > @atodorov thanks for the contribution!
> 
> You're welcome. I need you to click the "Merge" button though. I can't do that on my own.

Just had to wait for the CI to run first 🙂

**Pull request merged**
